amcli -u https://expnode.amaxscan.io system newaccount --stake-net "0.01 AMAX" --stake-cpu "0.01 AMAX" --buy-ram-kbytes 1 coinq admin.coinq AM75zEdxxNrDxvp7NbHkNatK1467cdHqChJfVhuJjAw2enKkDyBJ AM75zEdxxNrDxvp7NbHkNatK1467cdHqChJfVhuJjAw2enKkDyBJ
amcli -u https://expnode.amaxscan.io system newaccount --stake-net "0.01 AMAX" --stake-cpu "0.01 AMAX" --buy-ram-kbytes 1 coinq bp.coinq admin.coinq@active admin.coinq@active


amcli -u https://expnode.amaxscan.io push action amax.applybp addproducer '["amaxdevfunds",bp.coinq,"https://apollo.mypinata.cloud/ipfs/bafkreih72daoneipypub5zm2y45dant6ors4xpf6ie3cma33jaeoklsoxi","cn:CoinQ 交易所|en:CoinQ Exchange","web:https://www.coinq.com/|tw:https://x.com/CoinQExchange|tg: https://t.me/CoinQ_crypto|email:","","cn:节点产出80%由投票支持者划分，20%由节点维护者获得|en:80% of node output is divided by voting supporters, and 20% is obtained by node maintainers","cn:CoinQ 为致力于创建出一个可靠和创新的数字资产交易平台，帮助用户积累多元财富、拥有稳健的财务未来，并实现人生的财富追求。平台涵盖多个加密货币币种，包括比特币 (BTC)、以太币 (ETH) 、泰达币 (USDT)、Solana (SOL)、瑞波幣 (XRP)等数字资产，提供安全稳定、可持续、高度透明的加密货币交易服务。CoinQ 为客户创建一个优先考虑安全性、可靠性和创新的平台，实现在加密货币领域促进探索、机会和财富创造的愿景。通过加密货币，CoinQ致力帮助用户积累财富、拥有稳健的财务未来，并实现多元资产增值。让我们陪您一起踏上这段追求财富的征途，释放加密货币的无限潜力。|en:CoinQ is dedicated to creating a reliable and innovative digital asset trading platform that helps users accumulate a wealth of multi-assets, secure a stable financial future, and achieve their financial aspirations. The platform supports a variety of cryptocurrencies, including Bitcoin (BTC), Ethereum (ETH), Tether (USDT), Solana (SOL), Ripple (XRP), and many more, offering a safe, stable, sustainable, and highly transparent cryptocurrency trading service.CoinQ has built a platform that prioritizes security, reliability, and innovation, with a vision to foster exploration, opportunities, and wealth creation in the cryptocurrency space. We are committed to helping users accumulate wealth, secure a stable financial future, and achieve multi-asset appreciation through cryptocurrency. Let us accompany you on this journey of wealth creation, unlocking the limitless potential of cryptocurrency.","cn: |en: "]' -p amaxdevfunds
amcli -u https://expnode.amaxscan.io push action amax regproducer '[bp.coinq,"AM611usgqCch1BWGoSA6VLFNzvgSNWgrQhG5egnRry6zELjuRJvj","",0,8000]' -pbp.coinq
amcli -u https://expnode.amaxscan.io push action amax.applybp setstatus '[armoniaadmin,bp.coinq,"enable"]' -p armoniaadmin


amcli -u https://expnode.amaxscan.io push action amax.applybp addproducer '["amaxdevfunds",gsefundation,"https://apollo.mypinata.cloud/ipfs/bafkreie5udvsm6djnvzizd6egr57fl4wiq5rrbbuvkpj5ynk4otxmnq5fi","cn:美国全球稀缺能源基金会|en:Global Scarce Energy Foundation","web:|tw:|tg:|email:","","cn:节点产出80%由投票支持者划分，20%由节点维护者获得|en:80% of node output is divided by voting supporters, and 20% is obtained by node maintainers","cn:美国全球稀缺能源基金会（United States Global Scarce Energy Foundation）由李成洙博士于2015年在加拿大温哥华创立，致力于推动全球稀缺能源资源的保护、整合与创新性开发，促进传统矿业与前沿科技（如AI、区块链、智能金融）的深度融合，构建可持续发展的全球资源与智慧金融体系。现投资MES并与蒙古国算力中心、AQ索拉煤矿、希维能源等开展全球性战略合作。 支持全球矿产资源整合，包括煤矿、锂矿、金矿、稀土等关键战略资源，推动AI算力与能源开发协同发展，构建智能化绿色矿业新范式，引入区块链与RWA机制，强化矿产资产追踪与金融赋能，拥有跨国影响力，深度参与蒙古国、加拿大等资源经济体发展战略，机构合作网络 + 多边参与机制，基金会投资MES、蒙古国算力中心、AQ索拉煤矿、希维能源等开展全球性战略合作，推动“百矿计划”、智慧矿业、绿色能源与金融科技深度联动。通过举办国际峰会、政策倡导与项目投资，致力于构建“资源 × 技术 × 金融”的未来发展路径。全球稀缺能源基金会正以“资源安全 + 可持续金融”为核心驱动力，引领全球稀缺资源进入智慧化管理与生态共享的新纪元。|en:The United States Global Scarce Energy Foundation (GSEF) was founded by Dr. Lee Chengzhu in 2015 in Vancouver, Canada. The foundation is committed to the protection, integration, and innovative development of global scarce energy resources. It promotes deep integration between traditional mining and frontier technologies such as AI, blockchain, and intelligent finance, aiming to build a sustainable global resource and smart financial ecosystem. GSEF is currently an investor in MES and engages in strategic global partnerships with the Mongolia Computing Power Center, AQ Sora Coal Mine, and ShivEE Energy.Supports the integration of global mineral resources, including key strategic assets such as coal, lithium, gold, and rare earth elements.Promotes collaborative development between AI computing power and energy production, creating a new paradigm for smart and green mining.Introduces blockchain and RWA (Real World Asset) mechanisms to enhance traceability and financial empowerment of mineral assets.Possesses cross-border influence and is deeply involved in resource development strategies in countries like Mongolia and Canada.Builds institutional partnerships and multilateral participation networks.GSEF invests in MES, the Mongolia Computing Power Center, AQ Sora Coal Mine, ShivEE Energy, and others to promote the “Hundred Mines Plan,” smart mining, green energy, and the integration of financial technologies. Through hosting international summits, policy advocacy, and project investments, the foundation is driving the evolution of the “Resources × Technology × Finance” development model.GSEF is leading a new era of intelligent management and ecological sharing of global scarce resources, with resource security + sustainable finance at its core driving force.","cn: |en: "]' -p amaxdevfunds




amcli -u https://expnode.amaxscan.io push action amax regproducer '[amtychefidao,"AM88P4zervXbXniDNeV5ee8HnEagwTrC8Eg8PGqvvEHk8EGX7aga","",0,8000]' -pamtychefidao
amcli -u https://expnode.amaxscan.io push action amax.applybp setstatus '[armoniaadmin,amtychefidao,"enable"]' -p armoniaadmin
